sonatype-nexus-community/nexus-repository-helm

src/main/java/org/sonatype/repository/helm/internal/createindex/CreateIndexFacetImpl.java
src/main/java/org/sonatype/repository/helm/internal/createindex/CreateIndexServiceImpl.java
src/test/java/org/sonatype/repository/helm/internal/createindex/CreateIndexServiceImplTest.java

This pull request makes the following changes:
* Generate index.yaml at hosted repository creation time 
* Generated index.yaml will have empty entries yaml object
* Update unit test
It relates to the following issue #s:
* Fixes #23

Create initial index.yaml file for hosted repository

---

Dockerfile
pom.xml

Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
(brief, plain english overview of your changes here)
This pull request makes the following changes:
* Change Dockerfile to use new versions
* Upgrade parent-pom
(If there are changes to the UI, please include a screenshot so we
know what to look for!)

upgrade to nexus 3.18

---

.travis.yml
src/main/java/org/sonatype/repository/helm/internal/hosted/HostedHandlers.java

Fixing an error during plugin [temporary install](https://github.com/sonatype-nexus-community/nexus-repository-helm#temporary-install).
```
Error executing command: Error executing command on bundles:
Error starting bundle 251: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-helm [251](R 251.0): missing requirement [org.sonatype.nexus.plugins.nexus-repository-helm [251](R 251.0)] osgi.wiring.package; (&(osgi.wiring.package=jline.internal)(version>=2.14.0)) Unresolved requirements: [[org.sonatype.nexus.plugins.nexus-repository-helm [251](R 251.0)] osgi.wiring.package; (&(osgi.wiring.package=jline.internal)(version>=2.14.0))]
```
Related PR #52

Fix jline lib issue during bundle:start.

---

.circleci/config.yml
.github/CONTRIBUTING.md
.travis.yml
README.md

Adding `config.yml` for Circle CI integration
Ticket: https://issues.sonatype.org/browse/NEXUS-21033

Enabling Circle Ci integration

---

nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/internal/HelmHostedIT.java
nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/internal/HelmProxyIT.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/HelmRecipeSupport.groovy

https://issues.sonatype.org/browse/NEXUS-20949

NEXUS-20949: Asset and component removing

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/HelmRecipeSupport.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/hosted/HelmHostedRecipe.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/proxy/HelmProxyRecipe.groovy
nexus-repository-helm/src/test/java/org/sonatype/repository/helm/internal/HelmRecipeTest.java

Jira: https://issues.sonatype.org/browse/NEXUS-20839

NEXUS-20839 Helm plugin should be disabled when HA-C is enabled

---

pom.xml

https://issues.sonatype.org/browse/NEXUS-21686

NEXUS-21686 Move Helm to NXRM 3.20.0-SNAPSHOT

---

nexus-repository-helm/src/main/resources/static/rapture/NX/helm/controller/SearchHelm.js

https://issues.sonatype.org/browse/NEXUS-20980

NEXUS-20980 [Helm Bugs]Helm is not available in the Search group list

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/metadata/IndexYamlAbsoluteUrlRewriter.java
nexus-repository-helm/src/test/java/org/sonatype/repository/helm/internal/metadata/IndexYamlAbsoluteUrlRewriterTest.java
nexus-repository-helm/src/test/resources/org/sonatype/repository/helm/internal/metadata/indexWithCustomUrls.yaml

https://issues.sonatype.org/browse/NEXUS-20928
more info:
https://issues.sonatype.org/browse/NEXUS-21704

Nexus 20928 Support for secondary directory to get helm warehouse

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/HelmUploadHandler.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/AssetKind.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/HelmComponentMaintenanceFacet.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/HelmRecipeSupport.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/hosted/HelmHostedFacet.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/hosted/HelmHostedFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/hosted/HelmHostedRecipe.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/util/HelmAttributeParser.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/util/HelmPathUtils.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/util/ProvenanceParser.java
nexus-repository-helm/src/test/java/org/sonatype/repository/helm/internal/util/ProvenanceParserTest.java
nexus-repository-helm/src/test/resources/org/sonatype/repository/helm/internal/util/mysql-1.4.0.tgz.prov

https://issues.sonatype.org/browse/NEXUS-20927

NEXUS-20927 [Helm Features] Add provenance files support

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/HelmRestoreFacet.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/HelmUploadHandler.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/AssetKind.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/hosted/HelmHostedFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/proxy/HelmProxyFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/restore/HelmRestoreFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/util/HelmAttributeParser.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/util/HelmPathUtils.java
nexus-repository-helm/src/test/java/org/sonatype/repository/helm/internal/util/HelmAttributeParserTest.java
nexus-restore-helm/src/main/java/org/sonatype/nexus/blobstore/restore/helm/internal/HelmRestoreBlobStrategy.java
nexus-restore-helm/src/test/java/org/sonatype/nexus/blobstore/restore/helm/internal/HelmRestoreBlobStrategyTest.java

https://issues.sonatype.org/browse/NEXUS-21793

[Helm Bugs] Metadata self-repair does not work with provenance file

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/HelmAttributes.java

https://issues.sonatype.org/browse/NEXUS-21778

NEXUS-21778 [Helm Bugs] List of maintainers is not available

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/HelmAttributes.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/HelmFacet.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/HelmFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/createindex/CreateIndexFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/createindex/CreateIndexServiceImpl.java
nexus-repository-helm/src/test/java/org/sonatype/repository/helm/internal/createindex/CreateIndexServiceImplTest.java

https://issues.sonatype.org/browse/NEXUS-21813

NEXUS-21813 Helm can not add nexus hosted repository

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/HelmAttributes.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/createindex/CreateIndexServiceImpl.java
nexus-repository-helm/src/test/java/org/sonatype/repository/helm/internal/util/HelmAttributeParserTest.java

https://issues.sonatype.org/browse/NEXUS-22273

NEXUS-22273: Helm hosted does not work

---

pom.xml

https://issues.sonatype.org/browse/NEXUS-22578

NEXUS-22578: Include HELM community format to the NXRM

---

nexus-repository-helm-it/pom.xml
nexus-repository-helm/pom.xml
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/HelmRecipeSupport.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/hosted/HelmHostedRecipe.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/proxy/HelmProxyRecipe.groovy
nexus-restore-helm/pom.xml
pom.xml

Ticket: https://issues.sonatype.org/browse/NEXUS-22628
#113

NEXUS-22628 - fix warn on boot

---

README.md

https://issues.sonatype.org/browse/NEXUS-22654

NEXUS-22654: Update support version table for 3.21.0 release

---

Dockerfile

This pull request makes the following changes:
* Change the source of copy command in Dockerfile

Change source of copy command in Dockerfile

---

nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/rest/ResourceITSupport.java
pom.xml

https://issues.sonatype.org/browse/NEXUS-23275

NEXUS-23275: Support 3.22.0

---

nexus-repository-helm-it/pom.xml
nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/HelmITConfig.java
nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/internal/content/HelmClient.java
nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/internal/content/HelmContentITSupport.java
nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/internal/content/HelmContentProxyIT.java
nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/internal/content/fixtures/HelmRepoRecipes.groovy
nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/internal/content/fixtures/RepositoryRuleHelm.groovy
nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/internal/restore/HelmRestoreBlobIT.java
nexus-repository-helm/pom.xml
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/HelmAttributes.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/HelmContentFacet.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/metadata/IndexYamlAbsoluteUrlRewriter.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/package-info.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmContentFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmProxyFacet.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmProxyRecipe.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/store/HelmAssetBlobDAO.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/store/HelmAssetDAO.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/store/HelmComponentDAO.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/store/HelmContentRepositoryDAO.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/store/HelmStoreModule.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/metadata/IndexYamlAbsoluteUrlRewriterSupport.java
pom.xml

Implemented proxy endpoints in order to support new DB

NEXUS-23682: Implemented proxy endpoints in order to support new DB

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/createindex/CreateIndexFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmProxyFacet.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HostedHandlers.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/util/HelmPathUtils.java

Jira: https://issues.sonatype.org/browse/NEXUS-24452

NEXUS-24452: Added starting slash into asset path for sql database case

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmContentFacetImpl.java

Jira: https://issues.sonatype.org/browse/NEXUS-24453

NEXUS-24453: Fixed component name for new DB cases

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/package-info.java

Fix missing license headers

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmHostedRecipe.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmProxyRecipe.groovy

Ticket: https://issues.sonatype.org/browse/NEXUS-23687

NEXUS-23687 Search indexing for Helm

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/browse/HelmBrowseModule.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/browse/HelmBrowseNodeDAO.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/browse/HelmBrowseNodeGenerator.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmHostedRecipe.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmProxyRecipe.groovy

Ticket: https://issues.sonatype.org/browse/NEXUS-23686

NEXUS-23686 Browse nodes for Helm

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/metadata/IndexYamlAbsoluteUrlRewriterSupport.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/util/YamlParser.java

ticket: https://issues.sonatype.org/browse/NEXUS-24501
more details about this issue: https://securitylab.github.com/research/swagger-yaml-parser-vulnerability

NEXUS-24501: RCE in Helm

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/HelmContentFacet.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/HelmUploadHandler.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/browse/HelmBrowseModule.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/browse/HelmBrowseNodeDAO.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/browse/HelmBrowseNodeGenerator.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/createindex/CreateIndexFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/createindex/CreateIndexService.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/createindex/CreateIndexServiceImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmContentFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/createindex/HelmIndexInvalidationEvent.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/metadata/IndexYamlAbsoluteUrlRewriter.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/orient/createindex/CreateIndexFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/orient/metadata/IndexYamlBuilder.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/orient/proxy/HelmProxyFacetImpl.java
nexus-repository-helm/src/test/java/org/sonatype/repository/helm/internal/content/createindex/CreateIndexServiceImplTest.java
nexus-repository-helm/src/test/java/org/sonatype/repository/helm/internal/orient/metadata/IndexYamlAbsoluteUrlRewriterTest.java

Ticket: https://issues.sonatype.org/browse/NEXUS-23681

NEXUS-23681 Hosted metadata generation for Helm

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/HelmContentFacet.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/createindex/CreateIndexFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/createindex/CreateIndexServiceImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmContentFacetImpl.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmHostedRepositoriesApiResource.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmHostedRepositoriesApiResourceBeta.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmHostedRepositoriesApiResourceV1.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmProxyRepositoriesApiResource.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmProxyRepositoriesApiResourceBeta.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmProxyRepositoriesApiResourceV1.java
nexus-repository-helm/src/test/java/org/sonatype/repository/helm/internal/content/createindex/CreateIndexServiceImplTest.java
pom.xml

Ticket: https://issues.sonatype.org/browse/NEXUS-24692
Build: https://jenkins.ci.sonatype.dev/job/nxrm/job/nxrm3/job/nxrm-community-it/job/NEXUS-24692_fix_broken_api_from_3.26

NEXUS-24692: fix rest api changes

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/createindex/CreateIndexServiceImpl.java

Fixing index file wrong entry creating during chart upload.

NO_REF: index.yaml file should not be parsed during index build.

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmHostedRepositoriesApiResource.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmHostedRepositoriesApiResourceBeta.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmHostedRepositoriesApiResourceV1.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmProxyRepositoriesApiResource.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmProxyRepositoriesApiResourceBeta.java
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/rest/HelmProxyRepositoriesApiResourceV1.java

Making changes to accommodate to `nexus-internal` changes introduced at https://github.com/sonatype/nexus-internal/pull/5737

NO_REF: Adjusting inheritor classes to the changes in parent classes.

---

nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmHostedRecipe.groovy
nexus-repository-helm/src/main/java/org/sonatype/repository/helm/internal/content/recipe/HelmProxyRecipe.groovy

NEXUS-24855: Added missed ComponentMaintenanceFacet for Helm repo in SQL mode

NEXUS-24855: Added missed ComponentMaintenanceFacet for Helm repo in SQL mode
